import { useState } from "react";
import { motion } from "framer-motion";
import { AlertTriangle, ChevronDown, ChevronUp, FileText, Sparkles } from "lucide-react";

const sections = [
  {
    id: "ai-disclaimer",
    title: "AI Output Disclaimer",
    badge: "Required reading",
    badgeColor: "bg-amber-100 text-amber-700",
    content: [
      {
        heading: "What AI-generated designs are",
        body: "All images, floor plans, and layout concepts produced by GRUHAM are generated by AI models (text-to-image and image-to-image). They are illustrations intended to help you visualise and communicate ideas. They are NOT architectural drawings, structural drawings, or permit-ready documents.",
      },
      {
        heading: "What you must do before construction",
        body: "Before any construction begins, you must engage a licensed architect and a certified structural engineer. Their stamped drawings are legally required for building permits in India. GRUHAM's AI output cannot substitute for professional drawings.",
      },
      {
        heading: "Cost estimates are indicative",
        body: "GRUHAM's cost estimates are based on current market rate inputs for your city and finish level. They are indicative (±15%) and are NOT a contractor quotation. Actual costs depend on soil conditions, local bylaws, material price changes, design scope, and contractor terms.",
      },
      {
        heading: "Vastu guidance is informational",
        body: "GRUHAM's layout tools follow common Vastu Shastra zone guidelines. This is not a full Vastu compliance review. For authoritative Vastu guidance, consult a certified Vastu expert.",
      },
    ],
  },
  {
    id: "terms",
    title: "Terms of Service",
    badge: "Draft",
    badgeColor: "bg-blue-100 text-blue-700",
    content: [
      {
        heading: "Service description",
        body: "GRUHAM provides AI-assisted home design visualisation, indicative cost estimation, and a contractor discovery tool. The service is provided as a planning aid and does not constitute professional architectural, structural, legal, or financial advice.",
      },
      {
        heading: "Acceptable use",
        body: "You may use GRUHAM for personal residential planning purposes. You may not use the platform to collect or resell data, scrape contractor information, or misrepresent AI-generated images as professional drawings to third parties.",
      },
      {
        heading: "User content",
        body: "When you upload photos or sketches, you represent that you have the right to do so. GRUHAM uses your uploads solely to generate your requested designs and does not share them with third parties without your consent.",
      },
      {
        heading: "Limitation of liability",
        body: "GRUHAM is not liable for any construction decisions made based on AI-generated concepts or cost estimates. Always verify designs and costs with qualified professionals before committing to construction.",
      },
      {
        heading: "Full terms",
        body: "Comprehensive Terms of Service will be published at gruhamapp.com/terms before paid features launch. By using GRUHAM during this beta phase, you acknowledge that full legal terms are forthcoming.",
      },
    ],
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    badge: "Draft — DPDP Act aligned",
    badgeColor: "bg-green-100 text-green-700",
    content: [
      {
        heading: "What we collect",
        body: "Name, email, phone number (when you create an account), uploaded room/plot photos (used only for your design requests), and usage analytics (page views, feature usage — no personally identifiable data in analytics).",
      },
      {
        heading: "How we use it",
        body: "To generate your requested designs, to send you design results and account notifications, and to improve the product. We do not sell your personal data. We do not share your phone number or uploads with contractors without your explicit consent.",
      },
      {
        heading: "Contractor data",
        body: "Contractor phone numbers are masked in the UI until you choose to send a lead request. When you do, your basic query details (work type, city, budget band) are shared with that contractor — not your personal contact details unless you choose to include them.",
      },
      {
        heading: "Your rights (DPDP Act 2023)",
        body: "You have the right to access, correct, and delete your personal data. To request data export or deletion, contact hello@gruhamapp.com. We will respond within 30 days.",
      },
      {
        heading: "Data retention",
        body: "Your saved designs are kept until you delete them. Account data is retained while your account is active and for 90 days after deletion (for fraud prevention), then permanently erased.",
      },
      {
        heading: "Full policy",
        body: "A comprehensive Privacy Policy compliant with the Digital Personal Data Protection Act 2023 will be published before paid features launch.",
      },
    ],
  },
  {
    id: "refunds",
    title: "Refund Policy",
    badge: "Draft",
    badgeColor: "bg-purple-100 text-purple-700",
    content: [
      {
        heading: "Credit packs",
        body: "Unused credits in a credit pack are refundable within 7 days of purchase, provided fewer than 3 credits have been used. After 7 days or after 3+ credits used, no refund is issued. To request a refund, contact hello@gruhamapp.com with your order ID.",
      },
      {
        heading: "Monthly subscriptions",
        body: "Monthly plans can be cancelled at any time. You retain access until the end of your billing period. No prorated refunds are issued for partial months.",
      },
      {
        heading: "Failed renders",
        body: "If an AI render job fails (server error, provider outage), your credit is automatically refunded to your account within 24 hours. If it is not, contact support.",
      },
      {
        heading: "Payments not yet live",
        body: "Paid features are not yet available. This refund policy will apply when Razorpay checkout is enabled. There is nothing to refund at present.",
      },
    ],
  },
  {
    id: "contractor-terms",
    title: "Contractor Terms",
    badge: "Draft",
    badgeColor: "bg-orange-100 text-orange-700",
    content: [
      {
        heading: "Verification",
        body: "Contractors listed on GRUHAM as 'Verified' have submitted GSTIN/PAN, identity proof, at least 5 portfolio photos, and 3 client references. Verification does not guarantee work quality or guarantee any outcome. It means the listed checks were performed.",
      },
      {
        heading: "Lead purchase",
        body: "When a homeowner sends a quote request, contractors receive lead details (work type, city, budget band, timeline). Contractors pay per accepted lead or via a subscription plan. Leads are not guaranteed to convert.",
      },
      {
        heading: "Reviews",
        body: "Reviews are only permitted from homeowners who have marked a lead as 'hired'. Review manipulation (asking for fake reviews, threatening negative reviews) results in immediate account suspension.",
      },
      {
        heading: "Contractor marketplace",
        body: "The paid contractor marketplace is launching soon. Register your interest via the Contractor Registration page.",
      },
    ],
  },
];

function Section({ section }) {
  const [open, setOpen] = useState(section.id === "ai-disclaimer");

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between p-6 text-left hover:bg-gray-50 transition-colors"
        aria-expanded={open}
      >
        <div className="flex items-center gap-3">
          <FileText className="w-5 h-5 text-[#B8860B] flex-shrink-0" />
          <span className="font-serif text-xl font-bold text-[#1a1a1a]">{section.title}</span>
          <span className={`text-xs px-2 py-1 rounded-full font-medium ${section.badgeColor}`}>
            {section.badge}
          </span>
        </div>
        {open ? (
          <ChevronUp className="w-5 h-5 text-gray-400 flex-shrink-0" />
        ) : (
          <ChevronDown className="w-5 h-5 text-gray-400 flex-shrink-0" />
        )}
      </button>
      {open && (
        <div className="px-6 pb-8 space-y-6 border-t border-gray-100">
          {section.content.map((item) => (
            <div key={item.heading} className="pt-4">
              <h3 className="font-semibold text-[#1a1a1a] mb-2">{item.heading}</h3>
              <p className="text-gray-600 text-sm leading-relaxed">{item.body}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function Legal() {
  return (
    <div className="min-h-screen bg-[#FAF8F5] pt-24 pb-20">
      <div className="max-w-4xl mx-auto px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 bg-[#B8860B]/10 rounded-full px-4 py-2 mb-4">
            <Sparkles className="w-4 h-4 text-[#B8860B]" />
            <span className="text-[#B8860B] font-medium text-sm">Legal & Policies</span>
          </div>
          <h1 className="font-serif text-4xl font-bold text-[#1a1a1a] mb-4">
            Terms, Privacy & Disclaimers
          </h1>
          <p className="text-gray-600 max-w-2xl mx-auto">
            GRUHAM is in active development. Full legal documents will be published before paid
            features launch. The AI Disclaimer is final and applies immediately.
          </p>
        </motion.div>

        {/* Prominent AI disclaimer at top */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="flex items-start gap-4 bg-amber-50 border border-amber-200 rounded-2xl p-6 mb-8"
        >
          <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-amber-900 mb-1">AI output is concept-only</p>
            <p className="text-amber-800 text-sm leading-relaxed">
              All images, floor plans, and cost estimates produced by GRUHAM are AI-generated
              illustrations for planning purposes. They are not architectural drawings for
              construction. Always engage a licensed architect and structural engineer before building.
            </p>
          </div>
        </motion.div>

        <div className="space-y-4">
          {sections.map((section, i) => (
            <motion.div
              key={section.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 + i * 0.08 }}
            >
              <Section section={section} />
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mt-10 text-center text-gray-400 text-sm"
        >
          <p>Questions about these policies? Email{" "}
            <a href="mailto:hello@gruhamapp.com" className="text-[#B8860B] hover:underline">
              hello@gruhamapp.com
            </a>
          </p>
          <p className="mt-2">Last reviewed: August 2026</p>
        </motion.div>
      </div>
    </div>
  );
}
